### ISSUE TITLE
TypeError: Cannot read property 'match' of undefined at Object.exports.createDeployment

### ISSUE THREAD

**Issue by nick-moyer** [webfactory/create-aws-codedeploy-deployment#5]
I am encountering this error when running the workflow action. I'm able to manually create a deployment in AWS but not from the action as I get the following error when running the workflow. I'm not sure what I'm missing here so any help would be appreciated. 
```
Run webfactory/create-aws-codedeploy-deployment@v0.2.1
🎋 On branch 'aws', head commit c05d4429909487acca2b81f48117d78a2a14392a
💡 Using appspec.yml -> branch_config 'aws' for branch 'aws'
🎳 Using deployment group 'demo'
⚙️  Updated deployment group 'demo'
(node:2404) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of undefined
    at Object.exports.createDeployment (/home/runner/work/_actions/webfactory/create-aws-codedeploy-deployment/v0.2.1/dist/index.js:104:66)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2404) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2404) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

My appspec.yml:
```
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
hooks:
  AfterInstall:
    - location: ./install-app.sh
      timeout: 300
      runas: root

# This section controls the action:
branch_config:
  aws:
      deploymentGroupName: demo
      deploymentGroupConfig:
          serviceRoleArn: arn:aws:iam::555036407157:role/code-deploy-role
          ec2TagFilters:
                - { Type: KEY_AND_VALUE, Key: name, Value: AppServer }
      deploymentConfig:
          autoRollbackConfiguration:
              enabled: true
```

My release-aws.yml:
```
# This is a basic workflow to help you get started with Actions

name: Release-AWS

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ aws ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    -   uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
    -   uses: actions/checkout@v2
    -   id: deploy
        uses: webfactory/create-aws-codedeploy-deployment@v0.2.1
    -   uses: peter-evans/commit-comment@v1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            body: |
                @${{ github.actor }} this was deployed as [${{ steps.deploy.outputs.deploymentId }}](https://console.aws.amazon.com/codesuite/codedeploy/deployments/${{ steps.deploy.outputs.deploymentId }}?region=us-east-1) to group `${{ steps.deploy.outputs.deploymentGroupName }}`.
```
